name: Electre_Tri_B_MCDA-env

channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - matplotlib=3.4.3
  - numpy=1.21.2
  - math=3.9.10
  - jupyter=1.0.0
  - jupyterlab=3.0.14
  - ipywidgets=7.5.1
  - scipy=1.6.2
  - pandas=1.2.4

