name: Electre_Tri_B_MCDA_env

channels:
  - conda-forge

dependencies:
  - Cython=0.29.26
  - Pillow=8.4.0
  - XlsxWriter=3.0.2
  - attrs=21.2.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cycler=0.11.0
  - eccodes=1.4.0
  - findlibs=0.0.2
  - fonttools=4.28.3
  - ipywidgets=7.7.0
  - jupyter=1.0.0
  - jupyterlab=3.0.14
  - kiwisolver=1.3.2
  - matplotlib=3.5.1
  - numpy=1.21.4
  - packaging=21.3
  - pandas=1.3.5
  - pip=21.3.1
  - pycparser=2.21
  - pyparsing=3.0.6
  - pyproj=3.3.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - scipy=1.7.1
  - setuptools=57.4.0
  - six=1.16.0
  - wheel=0.37.0