name: Electre_Tri_B_MCDA-env

channels:
  - conda-forge

dependencies:
  - python=3.9.7
  - matplotlib=3.4.3
  - numpy=1.21.2
  - jupyter=1.0.0
  - jupyterlab=3.0.14
  - ipywidgets=7.7.0
  - scipy=1.7.1
  - pandas=1.3.3